#!/bin/sh
export TEXTDOMAIN=beryl.sh
export OUTPUT_CHARSET=UTF-8
#pinstall.sh

myicon="/usr/share/pixmaps/beryl-manager1.png"
mytitle="Beryl"
 
gtkdialog-splash -close box -icon "$myicon" -deco "$mytitle"  -timeout 6 -text "'$(gettext '5 sec. to restart X')'" &

sleep 5
restartwm openbox
