#!/bin/bash
#resizepfile.sh
#version=1.x
#language=english
#translator:don570

set -a

#general heading
LOC100="Resize personal storage file"

#first xdialog
LOC200="Sorry, you are not currently using a personal persistent"
LOC201="storage file. If this is the first time that you booted,"
LOC202="say from a live-CD, you are currently running"
LOC203="totally in RAM and you will be asked to create a personal"
LOC204="storage file when you end the session (shutdown the PC or"
LOC205="reboot). Note, the file will be named pup_save.2fs and"
LOC206="will be created in a place that you designate."
LOC207="If you have done a full install to a partition, or installed"
LOC208="such that personal storage is an entire partition, then"
LOC209="you will not have a pup_save.2fs file either."
LOC210="Press OK to exit..."



#second xdialog
LOC300="Your personal file is" # filename added
LOC301="You have" # size given
LOC302="Mbytes free space left in" # filename added
LOC303=", out of a total size of"  # size given
LOC304="Mbytes."
LOC305="The file" #filename added
LOC306="is actually stored on partition" #partition name added
LOC307="You have" #size given
LOC308="Mbytes space left in" #partition name added
LOC309="If you see that you are running low on space in"  # name of save file given
LOC310=", you can make it bigger,"
LOC311="but of course there must be enough space in" #partition name added
LOC312="PLEASE NOTE THAT AFTER YOU HAVE SELECTED AN OPTION BELOW,"
LOC313="NOTHING WILL HAPPEN. THE RESIZING WILL HAPPEN AT REBOOT."
LOC314="Select an option to make" # name of save file given
LOC315="bigger by that amount..."
LOC316="(note, this is one-way, you cannot make it smaller)"
LOC317="MB larger"
LOC318="MB larger  (1GB)"
LOC319="MB larger  (2GB)"
LOC320="MB larger  (4GB)"
LOC321="MB larger  (8GB)"

#fourth xdialog
LOC400="Okay, you have chosen to increase" # name of save file
LOC401="by" #size given
LOC402="Kbytes,"
LOC403="however as the file is currently in use, it will happen at reboot."
LOC404="Technical notes:"
LOC405="The required size increase has been written to file pupsaveresize.txt,"
LOC406="in partition" #name of partition
LOC407="(currently mounted on /mnt/home)."
LOC408="The file pupsaveresize.txt will be read at bootup and the resizing performed"
LOC409="then pupsaveresize.txt will be deleted."
LOC410="WARNING: If you have multiple pup_save files, be sure to select"
LOC411="the same one when you reboot."
LOC412="The change will only happen at reboot."
LOC413="Click OK to exit..."